<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/12/05 21:38:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
