<?php

/**
 * JobeetJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetJobTable
     */
    static public $types = array(
        'full-time' => 'Full time',
        'part-time' => 'Part time',
        'freelance' => 'Freelance',
    );

    public function getTypes()
    {
        return self::$types;
    }
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetJob');
    }

    public function getActiveJobs()
    {
        if (is_null($q))
        {
            $q = Doctrine_Query::create()
                ->from('JobeetJob j');
        }

        $q->andWhere('j.expires_at > ?', date('Y-m-d H:i:s', time()))
            ->addOrderBy('j.expires_at DESC');

        return $q->execute();
    }
    public function addActiveJobsQuery(Doctrine_Query $q = null)
    {
        // ...

        $q->andWhere($alias . '.is_activated = ?', 1);

        return $q;
    }
    public function retrieveBackendJobList(Doctrine_Query $q)
    {
        $rootAlias = $q->getRootAlias();
        $q->leftJoin($rootAlias . '.JobeetCategory c');
        return $q;
    }
    public function getForToken($query)
    {
        $affiliate = Doctrine_Core::getTable('JobeetAffiliate') ->findOneByToken($parameters['token']);
        if (!$affiliate || !$affiliate->getIsActive())
        {
            throw new sfError404Exception(sprintf('Affiliate with token "%s" does not exist or is not activated.', $parameters['token']));
        }

        return $affiliate->getActiveJobs();
    }
    public function  getForLuceneQuery($query)
    {
        $q = $this->createQuery();
        $q->where("position like '%".$query."%'");
        $q->orWhere("company like '%".$query."%'");
        $q->orWhere("location like '%".$query."%'");

        //$q = Doctrine_Core::getTable('Jobeetjob')->findBySql($dql);

        return $q->execute();
    }

}