<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/12/06 13:31:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'ypok',
  'name' => 'doctrine',
)),);
