<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/12/06 15:06:58
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
    'credentials' => 'admin',
    '.actions' => 
    array (
      'login_module' => 'default',
      'login_action' => 'login',
    ),
  ),
);
