<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/12/07 07:57:19
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
