<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/12/06 17:07:26
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
